session_name: cpp-opengl-glfw
windows:
  - window_name: editor-project
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/cpp-opengl-glfw/
      - nvim
  - window_name: shell
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/cpp-opengl-glfw

